;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		avy-goto-char-in-line
		counsel-M-x
		dumb-jump-go
		electric-newline-and-maybe-indent
		embrace-commander
		er/mark-outside-quotes
		eval-print-last-sexp
		god-local-mode
		god-mode-self-insert
		hydra-mc/mc/mark-next-like-this
		hydra-mc/nil
		kill-region
		sk/disable-god-mode
		sk/enable-god-mode
		sk/kill-region-or-backward-word
		sk/remove-mark
		sk/smarter-move-beginning-of-line
		sp-backward-delete-char
		sp-delete-char
		sp-kill-hybrid-sexp
		))

(setq mc/cmds-to-run-once
      '(
		))
