;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ivy-alt-done
	modalka-mode
	sk/smarter-move-beginning-of-line
	sp-backward-delete-char
	sp-backward-kill-word
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	delete-horizontal-space
	end-of-buffer
	iedit-mode
	mc/vertical-align-with-space
	org-self-insert-command
	))
