;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		ryo:04a1830bad47c97c575a7afb01ebd040:line/region
		ryo:1cf9c664ed81221b6fc344af519fce32:prev\ word
		ryo:848b1d4c3d1ae485709df48d826047bd:word
		ryo:8628beab3b735c231dec1454d5e52aaa:next\ like\ this
		ryo:dff4676e9e13ff5ff13e695aac818e69:next\ word
		ryo:efc40336295ecb767ca17f53da17c18d:start\ of\ line
		sk/enable-ryo-modal-mode
		sk/remove-mark
		sp-backward-delete-char
		))

(setq mc/cmds-to-run-once
      '(
		))
