;; Cursor type change
(setq-default cursor-type 'bar)

;; Key chords
(sk/require-package 'key-chord)
(sk/require-package 'key-seq)
(key-chord-mode 1)
(setq key-chord-two-keys-delay 0.5
      key-chord-one-key-delay 0.5)

(key-seq-define-global "//" 'counsel-locate)
(key-seq-define-global "==" 'indent-region)
(key-seq-define-global "[[" 'kmacro-start-macro)
(key-seq-define-global "]]" 'kmacro-end-macro)
(key-seq-define-global "``" 'sk/hydra-of-hydras/body)
(key-seq-define-global "q-" 'org-edit-src-code)
(key-seq-define-global "q." 'sk/hydra-of-repeat/body)
(key-seq-define-global "q=" 'sk/hydra-of-langs/body)
(key-seq-define-global "qa" 'sk/hydra-of-activate/body)
(key-seq-define-global "qb" 'sk/hydra-bookmarks/body)
(key-seq-define-global "qc" 'sk/hydra-comments/body)
(key-seq-define-global "qd" 'avy-goto-char-2)
(key-seq-define-global "qf" 'sk/hydra-of-navigation/body)
(key-seq-define-global "qg" 'sk/hydra-tags/body)
(key-seq-define-global "qh" 'avy-goto-char-in-line)
(key-seq-define-global "qj" 'sk/hydra-of-jump/body)
(key-seq-define-global "qk" 'sk/hydra-of-edits/body)
(key-seq-define-global "ql" 'avy-goto-line)
(key-seq-define-global "qm" 'kmacro-call-macro)
(key-seq-define-global "qn" 'kmacro-name-last-macro)
(key-seq-define-global "qo" 'sk/hydra-of-org/body)
(key-seq-define-global "qp" 'clipboard-yank)
(key-seq-define-global "qq" 'sk/hydra-of-motion/body)
(key-seq-define-global "qr" 'sk/hydra-rectangle/body)
(key-seq-define-global "qs" 'sk/hydra-of-search/body)
(key-seq-define-global "qt" 'sk/hydra-wgrep/body)
(key-seq-define-global "qv" 'sk/hydra-of-git/body)
(key-seq-define-global "qw" 'save-buffer)
(key-seq-define-global "qy" 'clipboard-kill-ring-save)
(key-seq-define-global "qz" 'sk/hydra-origami/body)
(key-seq-define-global "uu" 'sk/hydra-of-undo/body)
(key-seq-define-global "vv" 'sk/hydra-of-help/body)
(key-seq-define-global "xx" 'counsel-M-x)
(key-seq-define-global "yy" 'counsel-yank-pop)
(key-seq-define-global "zz" 'sk/hydra-of-windows/body)

(provide 'sk-interface)

;;; sk-interface.el ends here
