;; Cursor type change
(setq-default cursor-type 'bar)

;; God mode
(sk/require-package 'god-mode)
(require 'god-mode)
(global-set-key (kbd "<escape>") 'god-local-mode)
(global-set-key (kbd "<escape>") 'god-mode-all)
(setq god-exempt-major-modes nil
      god-exempt-predicates nil)
(defun sk/update-cursor ()
  (setq cursor-type (if (or god-local-mode buffer-read-only)
                        'box
                      'bar)))
(defun sk/god-binding-mode () (interactive)
       (if god-local-mode (god-mode-all)
         (setq god-mod-alist '((nil . "C-x C-z C-")))
         (god-mode-all)))
(add-hook 'god-mode-enabled-hook 'sk/update-cursor)
(add-hook 'god-mode-disabled-hook 'sk/update-cursor)
(define-key god-local-mode-map (kbd ".") 'repeat)
(define-key god-local-mode-map (kbd "i") 'god-local-mode)
(add-to-list 'god-exempt-major-modes 'paradox-menu-mode)
(add-to-list 'god-exempt-major-modes 'magit-status)
(add-to-list 'god-exempt-major-modes 'help-mode)
(add-to-list 'god-exempt-major-modes 'dired-mode)

;; Key binds
(sk/require-package 'bind-key)
(bind-keys*
 ("C-=" . avy-goto-line)
 ("C-q" . avy-goto-char)
 ("M-y" . counsel-yank-pop)
 ("C-c x" . counsel-M-x)
 ("C-c =" . indent-region)
 ("C-c r" . vr/query-replace)
 ("C-c i" . sk/hydra-of-edits/body)
 ("C-c o" . sk/hydra-of-org/body)
 ("C-c w" . sk/hydra-of-windows/body)
 ("C-c a" . sk/hydra-of-activate/body)
 ("C-c ]" . narrow-to-region)
 ("C-c [" . widen)
 ("C-c m" . sk/hydra-of-macros/body)
 ("C-c j" . sk/hydra-of-jump/body)
 ("C-c /" . counsel-locate)
 ("C-c l" . sk/hydra-of-langs/body)
 ("C-c `" . sk/hydra-of-hydras/body)
 ("C-c a" . sk/hydra-of-activate/body)
 ("C-c e" . sk/hydra-wgrep/body)
 ("C-c g" . sk/hydra-of-git/body)
 ("C-c h" . sk/hydra-of-help/body)
 ("C-c s" . sk/hydra-of-search/body)
 ("C-c t" . sk/hydra-tags/body)
 ("C-c y" . clipboard-kill-ring-save)
 ("C-c p" . clipboard-yank)
 ("C-c f" . sk/hydra-of-navigation/body)
 ("C-z C-x" . counsel-M-x)
 ("C-z C-=" . indent-region)
 ("C-z C-r" . vr/query-replace)
 ("C-z C-i" . sk/hydra-of-edits/body)
 ("C-z C-o" . sk/hydra-of-org/body)
 ("C-z C-w" . sk/hydra-of-windows/body)
 ("C-z C-a" . sk/hydra-of-activate/body)
 ("C-z C-]" . narrow-to-region)
 ("C-z C-[" . widen)
 ("C-z C-m" . sk/hydra-of-macros/body)
 ("C-z C-j" . sk/hydra-of-jump/body)
 ("C-z C-/" . counsel-locate)
 ("C-z C-l" . sk/hydra-of-langs/body)
 ("C-z C-`" . sk/hydra-of-hydras/body)
 ("C-z C-a" . sk/hydra-of-activate/body)
 ("C-z C-e" . sk/hydra-wgrep/body)
 ("C-z C-g" . sk/hydra-of-git/body)
 ("C-z C-h" . sk/hydra-of-help/body)
 ("C-z C-s" . sk/hydra-of-search/body)
 ("C-z C-t" . sk/hydra-tags/body)
 ("C-z C-y" . clipboard-kill-ring-save)
 ("C-z C-p" . clipboard-yank)
 ("C-z C-f" . sk/hydra-of-navigation/body))

(provide 'sk-interface)

;;; sk-interface.el ends here
