;;; sk-modal-modalka-which-key.el --- Global settings -*- lexical-binding: t; -*-

;;; Commentary:

;; which key for modalka bindings

;;; Code:

(which-key-add-key-based-replacements
  "ESC" "toggle mode"
  "DEL" "smart del"
  "TAB" "smart tab"
  "RET" "smart enter"

  "0" "0"
  "1" "1"
  "2" "2"
  "3" "3"
  "4" "4"
  "5" "5"
  "6" "6"
  "7" "7"
  "8" "8"
  "9" "9"

  "h" "prev char"
  "j" "next line"
  "k" "prev line"
  "l" "next char"
  "e" "next word"
  "b" "prev word"
  "n" "next history item"
  "N" "prev history item"
  "{" "next para"
  "}" "prev para"
  "0" "start of line"
  "$" "end of line"
  "(" "start of sentence"
  ")" "end of sentence"
  "G" "end of file"
  "/" "search"
  "d" "delete selection"
  "y" "copy selection"
  "p" "paste"
  "P" "paste history"
  "x" "delete char"
  "D" "delete rest of line"
  "M" "modify argument"
  "z" "scroll center/top/bot"
  "Z" "zoom into window"
  "H" "scroll left"
  "J" "scroll down"
  "K" "scroll up"
  "L" "scroll right"
  "'" "org edit separately"
  "q" "start macro"
  "Q" "end macro"
  "." "repeat prev command"
  "?" "top level bindings"
  "v" "start selection"
  "R" "overwrite mode"
  "V" "start rectangle selection"
  "X" "exchange point and mark"
  "+" "set bookmark"
  "=" "indent region"
  "\\" "C-c C-c"
  "!" "shell command"
  "&" "async shell command"
  "<" "goto last change"
  ";" "back from tag"
  "," "goto global change"

  "g" "global prefix"
  "g g" "start of file"
  "g u" "downcase region"
  "g U" "upcase region"
  "g T" "titlecase region"
  "g m" "make frame"
  "g M" "name frame"
  "g k" "kill frame"
  "g j" "jump frame"
  "g f" "file/url at cursor"
  "g o" "eval elisp"
  "g w" "vertical split win"
  "g W" "horizontal split win"
  "g S" "split line"
  "g q" "format para"

  "i" "expand prefix"
  "i a" "expand entire buffer"

  "[" "backward nav/edit"
  "[ [" "widen region"

  "]" "forward nav/edit"
  "] ]" "narrow region"

  ":" "extended prefix"
  ": q" "quit emacs"

  "SPC" "custom prefix"
  "SPC j" "jump to cmd"
  "SPC f" "find file"
  "SPC a" "switch buffers"
  "SPC d" "dired"
  "SPC k" "close buffer"
  "SPC w" "save buffer"
  "SPC c" "load theme"
  "SPC q" "quit window"
  "SPC i" "edit results"
  "SPC h" "org refile"
  "SPC o" "over/abort"
  "SPC g" "follow"
  "SPC SPC" "search")

(provide 'sk-modal-modalka-which-key)
;;; sk-modal-modalka-which-key.el ends here
